manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/alescito
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
